### ISSUE TITLE
Favicon w/JetPack Icon Feature

### ISSUE THREAD

**Issue by bkonia** [bueltge/wordpress-multisite-enhancements#13]
Can you make the favicon automatically work with the JetPack Icon feature?

**Comment by bueltge** [comment]
Back to core, release via icon feature of WP 4.3 - - https://core.trac.wordpress.org/changeset/32994

**Comment by wisdomtooth** [comment]
Has this been included in the production version? It doesn't seem to be working.

**Comment by bueltge** [comment]
Yes. But not with the help from Jetback. The solution is the new favicon function, feature from the WordPress core, since wp 4.3 public. You can set a favicon with the Customizer function and the plugin use it.
