### ISSUE TITLE
Plugin retrieves favicons of sites which do not appear in admin bar

### ISSUE THREAD

**Issue by JustThomas** [bueltge/wordpress-multisite-enhancements#25]
My admin bar only shows 6 websites under the "My Sites" section, but the "Multisite Enhancements" plugin retrieves the paths to the favicons of all >100 sites in my network. This results in >100 single DB queries which retrieve the path to a favicon which never appers in my admin bar.

You could probably save a lot of DB queries by replacing `wp_get_sites` with `get_blogs_of_user` in `Multisite_Add_Admin_Favicon::set_admin_bar_blog_icon()`.

**Comment by bueltge** [comment]
Thanks for this helpful hint, changed in the new version [1.3.5](https://github.com/bueltge/wordpress-multisite-enhancements/releases/tag/1.3.5).
