### ISSUE TITLE
Adding some of the features into the Top Admin Tool bar core project?

### ISSUE THREAD

**Issue by paaljoachim** [bueltge/wordpress-multisite-enhancements#26]
Hey

Check out:
https://make.wordpress.org/core/2016/05/23/may-20-toolbar-and-admin-menu-meeting-summary/

Perhaps this is something you guys can take a closer look at?

**Comment by bueltge** [comment]
Hey Joachim,
I think different points of the plugin are really helpful for the core, not all, bot some classes.
What do you think ? Should we add new issues with the possibilities or have you active issues for this enhancements?

Currently I work seldom on the core, but current only on the tab in the site-settings and the settings api for the multisite.

**Comment by paaljoachim** [comment]
Hey Frank

What about adding a comment to the make WordPress post I mentioned? Suggesting to add some features. It would be great to get a multisite developer to help out with some of the existing as well as adding some new issues to the top admin toolbar. I also think that a few of the features from David Deckers plugin should be added: https://wordpress.org/plugins/multisite-toolbar-additions/screenshots/
If you could help out with some of the multisite enhancements that would be very helpful.

I am thinking that you could also attend a multisite slack chat in regards to settings api for multisite. As I believe it has come up a few times.
https://make.wordpress.org/core/2016/05/25/multisite-office-hours-recap-may-23-2016/

**Comment by bueltge** [comment]
But my enhancements are not in the priority for the Admin Bar, without the Favicon Feature. But I think this feature is not a proposal for the core, is more a playground and cost resources, there I don't see in the core. 

The other classes are really helpful, especially the list usage of plugins, his usage in the site on the overview and also this for themes.

I read also, seldom, the chat and make posts. Also I check this two tickets [#31274](https://core.trac.wordpress.org/ticket/31274), [#15800](https://core.trac.wordpress.org/ticket/15800) and Dominik inform me about this topics. I have privately a important interest on the settings api for the core.

**Comment by paaljoachim** [comment]
See if there are things that you can add to the discussion/project. If not then that is alright.

**Comment by bueltge** [comment]
You have right. I like it to add ideas. But I understand this post as note for Admin Bar topics, or see you this other? Maybe I overlook a topic in the post.

**Comment by paaljoachim** [comment]
I am thinking that some of the features in your plugin could be added into core. I can suggest it in the multisite slack channel. Some of the top admin features you have in your plugin could be added to the core top admin bar. But we can just hold off for now. The trac ticket https://core.trac.wordpress.org/ticket/32678 is very very long and hopefully adjustments to multisite top admin toolbar will also be added. You can just close this issue for now..

**Comment by bueltge** [comment]
Hi Paal Joachim,
I understand the issue only for the topic Admin Bar. If it not right, please reply again to me!
This plugin here have much more helpers for the admin area, the network pages and not the admin bar.

Only two features, the favicon and the status if a site are admin bar items.
But I'm not really sure, that are topics for the core. This are hard changes for a lot of users and also for the performance. If the users have a lot of sites in the network it is a problem, maybe. It is not easy to test this and the core functions to get relevant data are not really good, to mad for bigger sites with a lot of sites.
