### ISSUE TITLE
Please provide more examples

### ISSUE THREAD

**Issue by yossely** [bueltge/wordpress-multisite-enhancements#28]
I've seen the documentation but it's not clear enough, it does not have examples for every hook.

Could you improve the documentation?

**Comment by bueltge** [comment]
For which goal do you need examples?

**Comment by yossely** [comment]
I need to set different favicon for each site on Admin bar, under 'My Sites' list

**Comment by bueltge** [comment]
The easiest way is to use the core function. The Customizer allow it to add a custom favicon for each site in frontend. The plugin check this and use it as favicon also for the admin bar, no coding, way to use. 
Maybe this helps you?
