### ISSUE TITLE
wp_get_sites is deprecated since version 4.6.0! Use get_sites() instead.

### ISSUE THREAD

**Issue by grappler** [bueltge/wordpress-multisite-enhancements#29]
I get the warning in WP 4.6.1 when I activate a plugin.

https://github.com/bueltge/wordpress-multisite-enhancements/blob/master/inc/autoload/class-add-plugin-list.php#L221

**Comment by bueltge** [comment]
Moin @grappler 
I know, but thanks a lot for the hint to change this.

But you should only get a warning, no error message. Maybe you mean a warning?

**Comment by grappler** [comment]
Yes, sorry, I meant warning.

**Comment by bueltge** [comment]
Hey @grappler 
please can you test the current version from github?
I have change this, now I use a solid method to rule them all in this context. Also I have remove the plugin search #30 , there is also in the core from Konstantin. But the search works not on themes. The point, that I add a custom function to search fast about all themes about the title of each theme.
THanks!
