### ISSUE TITLE
plugin lost a core feature

### ISSUE THREAD

**Issue by arcesala** [bueltge/wordpress-multisite-enhancements#32]
Hi all!
I've updated the plugin to its latest version (1.3.6) and now on the list of plugins, it doesn't show the site were the plugins have been enabled (which is one of the more important features of the plugin).
Thanks!

**Comment by bueltge** [comment]
Thanks for you issue, I can check this in 10 days, I'm currently on  travelling without a client.

**Comment by slistudios** [comment]
Looking forward to the update. Great plugin, thank you.

**Comment by bueltge** [comment]
@arcesala Please can you test the current download, master branch? The problem should fixed now. Thanks for your feedback.

**Comment by arcesala** [comment]
@bueltge Frank, can you please provide me with the steps to implement this? This is the first time for me using github so I don't really know how to test this. Apologies!

**Comment by bueltge** [comment]
Yes, welcome. 
You should download the current master - https://github.com/bueltge/wordpress-multisite-enhancements/archive/master.zip

The package is now on your local client. Update your installation with this version, overwrite all files in the directory of the plugin, on default in `wp-content/plugins/` with the files of the zip, package.
The package have much more files, only interesting for development, but they are not a problem on your install. After you have overwrite the files, you should find active the version 1.3.7-RC1 ion your plugin view of your install.

**Comment by arcesala** [comment]
Thanks Frank! I've done it already and it does look ok. The sites list is back!

**Comment by bueltge** [comment]
Thanks a lot.
