### ISSUE TITLE
different init for SSL identifier class

### ISSUE THREAD

**Issue by cfoellmann** [bueltge/wordpress-multisite-enhancements#35]
Is there any explanation why the `class Multisite_Add_Ssh_Identifier` is init different from the other classes?
https://github.com/bueltge/wordpress-multisite-enhancements/blob/master/inc/autoload/class-add-ssl-identifier.php#L10-L14

**Comment by bueltge** [comment]
Yes, my knowledge have changed. This init is solid and not only use as singleton. I would write no singletons for longer time, but older code use a lot of this pattern, also my older class ass the ssh identifier.

**Comment by cfoellmann** [comment]
thx
