### ISSUE TITLE
List of sites per theme/plugin can get long

### ISSUE THREAD

**Issue by cfoellmann** [bueltge/wordpress-multisite-enhancements#40]
I think the list of sites added to the plugins and themes site can get quiet long.
Is that a problem for anyone? Maybe hiding the list and opening only onClick or in a modal would be good for big sites

**Comment by bueltge** [comment]
Yes, you have right.
Currently I haven't negative feedback about this feature, so that I don't see a change for me. However request are really welcome! Buy the ways, thanks for the other changes! :heart:

**Comment by bueltge** [comment]
The new change fixed this issue.
Thanks @cfoellmann for the idea and @n-goncalves for the request.
