### ISSUE TITLE
Don't hard-code RAM number format

### ISSUE THREAD

**Issue by GaryJones** [bueltge/wordpress-multisite-enhancements#47]
[This line](https://github.com/bueltge/wordpress-multisite-enhancements/blob/6a8b7f72d292f16da7655454909383b6e4dea820/inc/autoload/class-change-footer-text.php#L119) effectively hard-codes the number format for the RAM, which means that it looks odd in other locales (like British English), where we'd use a `.` as the decimal point, and `,` as the thousands separator.

**Comment by bueltge** [comment]
Hi @GaryJones 
Thanks for your review and hint. You have right, however is was not on my focus.
Now it should display in depend from the location and also translatable. However is not really formatted for a translation, need a rewrite for this context area, i mean.

include commit  3024f79f70c8f03b73395054e6fd0c1e3a8f999a
