### ISSUE TITLE
Footer abbreviation title text is not internationalised

### ISSUE THREAD

**Issue by GaryJones** [bueltge/wordpress-multisite-enhancements#48]
While it's fine for `en-*`, it may look odd for the tooltips from [here](https://github.com/bueltge/wordpress-multisite-enhancements/blob/6a8b7f72d292f16da7655454909383b6e4dea820/inc/autoload/class-change-footer-text.php#L119-L124) being shown in English for a non-English admin.

**Comment by bueltge** [comment]
# also changed, discussed in #47
