### ISSUE TITLE
Transients in Debug mode

### ISSUE THREAD

**Issue by cfoellmann** [bueltge/wordpress-multisite-enhancements#49]
The notice `Multisite Enhancements: Delete site transients for the plugin usage to help on development, debugging. The constant WP_DEBUG is true.` is very irritating.

It does mean: The transients were deleted!?
My alternative:

`Multisite Enhancements: [WP_DEBUG = true] Site transients (plugin usage caching) were cleared to help with development, debugging.`

Same for themes.

**Comment by bueltge** [comment]
The hint mean that the plugin don't store the data in cache, always loading without usage of transient cache.
Maybe you can help to create an more understanding message.

**Comment by cfoellmann** [comment]
Ok. Then I was totally wrong. Seems to be harder to understand than I thought.

I will try to go over the UI as soon as I have some time.
That will kill the translations 😕 that’s bad

**Comment by mindctrl** [comment]
Maybe something like this?

`Multisite Enhancements: Plugin usage information is not cached while WP_DEBUG is true.`

**Comment by cfoellmann** [comment]
@mindctrl that is what I was thinking about.

Only problem with „debugging“ the strings of the plugin is that translations will be invalidated and have to be done for all changed Strings again

**Comment by bueltge** [comment]
Christian Foellmann <notifications@github.com> schrieb am Di., 26. Juni
2018, 15:32:

**Comment by cfoellmann** [comment]
Solved
