### ISSUE TITLE
Alphabetize sites on which plugins are active

### ISSUE THREAD

**Issue by ahmed-sigmalux** [bueltge/wordpress-multisite-enhancements#50]
The feature that shows which sites a plugin is active on is very helpful. The list of sites, however, is shown in order of site ID instead of alphabetically by site name.

Would it be possible to alphabetize the list of sites by name?

**Comment by bueltge** [comment]
Currently add the plugin only the ID, the view for active is an core feature. Maybe we should add a script for custom filter of the table?

**Comment by bueltge** [comment]
I will close this issue for now, so I get no feedback from other users for this requirement.
