### ISSUE TITLE
Admin bar features do not scale very well

### ISSUE THREAD

**Issue by websupporter** [bueltge/wordpress-multisite-enhancements#52]
We use this plugin in a big multisite with 50+ sites. Some users are registered to all 50+ sites.

Two features of this plugin are now very time consuming:
`enhance_network_blog_admin_bar()`
`set_admin_bar_blog_icon()`

The first adds the "Manage Comments"-menu item to the admin bar. Therefore it needs to run through all sites (`switch_to_blog()`) to see if the user is able to manage comments in order to print the comments.

The 2nd prints the favicon for a site (if given) in the admin bar. Therefore it needs to run through all sites and check for a favicon.

For our case, we do not need those features, so it would be good, if those features could be optional.

Alternatively (or additional), maybe there could be a better strategy using `switch_to_blog()`, so the calls could be reduced. I am not quite sure, how caching could be applied here given the comments count needs to be quite up to date.

**Comment by websupporter** [comment]
```
add_filter(
  'multisite_enhancements_autoload',
  function($files) {
  
        unset($files['class-add-admin-favicon.php']);
        unset($files['class-admin-bar-tweaks.php']);
        return $files;
  }
);
```

is actually sufficient for our needs I think.

**Comment by bueltge** [comment]
hello @websupporter 
thanks for usage the old one and your feedback. The features haven't any caching or better approach as switch to blog core feature. So it is current the best way to switch of via hook. Also as hint in the context of large multisite see https://github.com/bueltge/wordpress-multisite-enhancements/wiki/Large-Network-Problem

The plugin needs a refactoring, more solid, more focus on speed and more focus on testing, switch of the singletons.

**Comment by cfoellmann** [comment]
Just like @bueltge said, there is no way to cache that.

Meta data for sites (blogs) is coming to multisite some time in the future. Maybe that can help us with stuff like this.

**Comment by bueltge** [comment]
as hint the link about the topic, that @cfoellmann mentioned https://make.wordpress.org/core/2019/01/28/multisite-support-for-site-metadata-in-5-1/
