### ISSUE TITLE
WP icon disappearing from dashboard

### ISSUE THREAD

**Issue by wjkowalski** [bueltge/wordpress-multisite-enhancements#53]
I just noticed yesterday that the WP icon typically found in the top left-hand corner of the dashboard was not displaying in my multisite. Instead, I was seeing the address of the image printed out as text.

I did some playing around with plugins and disabled one called Branda by WPMU. This caused the text string to disappear, but there was no image at all then.

To experiment further, I disabled Multisite Enhancements and the icon immediately came back. Re-enabling it caused it to disappear again, and disabling it again caused the icon to return again. 

This is the extent of the testing I've been able to do. I looked at the styles in Inspector for id="wp-admin-bar-wp-logo" and I see that this list item is disappearing when the plugin is enabled, so I don't think the problem is that it is somehow being hidden. It is just not being called.

**Comment by bueltge** [comment]
Hi @wjkowalski 
That's right. The plugin remove this item, the menu item include the icon and the sub-menu items.
So if you will not hide theme, please remove this functionality with a custom addtional plugin, see https://github.com/bueltge/wordpress-multisite-enhancements/wiki/Remove-features for remove a class with all features. To remove only the hidding of the WP logo and his sub.items use the hook ( `multisite_enhancements_remove_wp_admin_bar `)[ https://github.com/bueltge/wordpress-multisite-enhancements/blob/master/inc/autoload/class-add-admin-favicon.php#L229] and set to false. 

```php
add_filter( 'multisite_enhancements_remove_wp_admin_bar', function() { return false; } );
```
