### ISSUE TITLE
Admin bar submenu's don't work correctly anymore.

### ISSUE THREAD

**Issue by JoryHogeveen** [bueltge/wordpress-multisite-enhancements#55]
The solution added in the latest version to make the sites adminbar menu scrollable isn't valid.
This change has multiple issues:
- Overwrites CSS for ALL submenu's in the admin bar
- Multiple submenu's (3rd level) cannot be visible
- Fixed widths for submenu's instead of the slick auto-widths approach of WP core itself.
- Menu's on the right side are totally messed up.

A similar solution has been rejected by WP core due to it's limitations. An absolute positioned element (2nd submenu) cannot be visible outsite of a scrollable container.
The solution isn't to enable overflow scrolling on this element but to have some sort of Javascript scrolling which modifies the position of the whole sites submenu.

**Comment by JoryHogeveen** [comment]
Ticket WP Core: https://core.trac.wordpress.org/ticket/15317

**Comment by cfoellmann** [comment]
This is valid. Breaks my admin bar, too.

**Comment by derpixler** [comment]
Thanks for your Feedback.

I'll think about a quick solution and i'm sure @bueltge will do a rollback.

**Comment by bueltge** [comment]
@JoryHogeveen @cfoellmann do you have screenshots for me to understand the problem? I can't see any problem in my tests, however I haven't currently any site with more as 10 sites in the network.

**Comment by bueltge** [comment]
@derpixler We have also a break with this new css for the light theme. Users there use not the dark side of <del>life</del> WordPress, have issues inside the design:
>It’s setting the background colour of some admin bar menus to be the dark style – it’s not compatible with the Light style.
>It’s also setting the width of the profile drop down which is causing an offset to the left of the profile drop down

**Comment by bueltge** [comment]
@derpixler Please use the branch [`scrollbale-networkmenu`](https://github.com/bueltge/wordpress-multisite-enhancements/tree/scrollbale-networkmenu) for changes on this topic, Issue #55 and PR #54

**Comment by bueltge** [comment]
Revert is done, new release 1.5.1 should get the last stable version with small fixes for php notes and the transient topic.

**Comment by derpixler** [comment]
@bueltge i'll fix it asap

**Comment by JoryHogeveen** [comment]
Issue on the right side:
![image](https://user-images.githubusercontent.com/826148/53375567-e814df80-395b-11e9-8357-66c534c40e98.png)

Width issue:
![image](https://user-images.githubusercontent.com/826148/53375607-0549ae00-395c-11e9-86ca-49affec33421.png)

I can't find an example of a 3rd level submenu as fast but as I've seen the CSS this simply won't work and WP allows for "infinite" submenus.

On a side note, IMO this is not something this plugin _should_ do at all. This is an issue repeatedly reported in WP core and it's in discussion for a fix but it's simply not something that can be fixed in a general compatible way.
@derpixler If you have a correct fix that would work with all plugins I suggest you submit it to the WP core ticket: https://core.trac.wordpress.org/ticket/15317

**Comment by JoryHogeveen** [comment]
Another suggestion. If you disagree and this gets included in this plugin please add a filter to disable it.

**Comment by bueltge** [comment]
@JoryHogeveen Currently each class have a hook to deactivate ([How to](https://github.com/bueltge/wordpress-multisite-enhancements/wiki)). Also we have here and there hooks to remove or change the default. So we should also use this hook to deactivate this class and separate it in a single class without the current CSS additional.

**Comment by bueltge** [comment]
Hello @JoryHogeveen hello @cfoellmann 
Would you test the branch https://github.com/bueltge/wordpress-multisite-enhancements/tree/scrollbale-networkmenu that should include a solution for the scrollablke menu. Thanks for your feedback!

**Comment by JoryHogeveen** [comment]
Hi @bueltge 
I'm still not a fan of this addition as its more of a hack instead of a fix.
The latest changes applies the same structural issues as I mentioned before, but then only to the "My Sites" submenu.
Also, the color changes aren't in line with how the default submenus of de WP Toolbar look AND aren't compatible with other admin themes. (Why are there color changes at all?? WP already has all the styling in place)

For me, this is far from ready.

And even more important: this should be fixed in WP core, NOT a plugin. There are numerous active WP Core tickets related/similar to this issue so I suggest to add patches there and enhance the overall WP Toolbar menu.

**Comment by bueltge** [comment]
Thanks a lot @JoryHogeveen Really helpful.

**Comment by JoryHogeveen** [comment]
No problem! In addition to the color changes. If anyone wants the admin color scheme to be different they can create their own color scheme according to WP guidelines. A plugin shouldn't affect this.

**Comment by bueltge** [comment]
So we don't get any feedback or development I will close this issue and we leave the menu without scrolling.
