### ISSUE TITLE
Single Signon

### ISSUE THREAD

**Issue by sebastienserre** [bueltge/wordpress-multisite-enhancements#58]
Hello,

It should be great if you plugin privides whta this one (not maintened) do :
https://github.com/voceconnect/wp-multisite-sso

Thanks for your job

**Comment by bueltge** [comment]
Hi and thanks for your feedback.
However I think this should more a single solution. My plugin is more in the context to helps Administrators to get more overview, content about the Multisite. The SSO is a other context, change the usage of the network for all users and is not always in focus of each Multisite.

So I close them, but feel free to hint me if you familiar with my points to close this issue.
