### ISSUE TITLE
broken sites-menu sind Wordpress V5.3

### ISSUE THREAD

**Issue by brrrrrrrt** [bueltge/wordpress-multisite-enhancements#61]
the picture say it all:

![Bildschirmfoto von 2019-11-13 21-34-16](https://user-images.githubusercontent.com/4489013/68802597-836ef180-065e-11ea-9745-f8a95a64e121.png)

**Comment by bueltge** [comment]
What' the trigger of that, on my install after update to version 5.3 of WP works without problems?
![image](https://user-images.githubusercontent.com/133425/68833892-da9fb100-06b4-11ea-92d8-0dd5357fa5b5.png)

**Comment by JoryHogeveen** [comment]
This is due to the extra info icons.
While it uses WP core icons the WP 5.3 update doesn't fully cover the fixes.
One fix is to wrap these icons and add `overflow: hidden`.

**Comment by plerix** [comment]
I just discover the same problem ;)

**Comment by bueltge** [comment]
It would be great if you have the possibility to test the new release before I will roll out the new version. Feedback would be great.
The download is here: overwrite all PHP files or add as new folder, rename the old one.
https://github.com/bueltge/wordpress-multisite-enhancements/releases/tag/1.5.2

**Comment by bueltge** [comment]
With the new releaser should the topic fixed. Thanks for your contribution. :heart:

**Comment by plerix** [comment]
Great job. Tanks !

 

De : Frank Bültge <notifications@github.com> 
Envoyé : vendredi 15 novembre 2019 12:03
À : bueltge/wordpress-multisite-enhancements <wordpress-multisite-enhancements@noreply.github.com>
Cc : Plerix <philippe.lenders@philix.be>; Comment <comment@noreply.github.com>
Objet : Re: [bueltge/wordpress-multisite-enhancements] broken sites-menu sind Wordpress V5.3 (#61)

 

With the new releaser should the topic fixed. Thanks for your contribution. ❤️

**Comment by brrrrrrrt** [comment]
> With the new releaser should the topic fixed. 

thank you very much for this quick fix! works like a charm :)
