### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by knutsp** [bueltge/wordpress-multisite-enhancements#64]
The n-strings "Active on %s site" / "Active on %s sites" are used both for plugins and themes. However, the word active (single or plural), may not be translated to the same word when meaning plugins as when meaning themes (different gender association).

So, suggest split into to two separate n-pair of strings, with contexts themes and plugins.

**Comment by bueltge** [comment]
@knutsp The string is separately in plugins and theme lists. I add now a hint for translators, maybe this helps to translate it more easily and list it separately on the translation option on wp.org.

**Comment by knutsp** [comment]
Yes, if they have different context (theme|plugin) then they will b different strings for translation. Do not only add hint/comment, but use the context aware translation functions.

**Comment by bueltge** [comment]
And c0d9c9d239bfd806ed0b5d0b2142ffe3e12fc6df
