### ISSUE TITLE
missing Favicons

### ISSUE THREAD

**Issue by brrrrrrrt** [bueltge/wordpress-multisite-enhancements#68]
since some recent update, all Favicons are gone:

![favicons-bug](https://user-images.githubusercontent.com/4489013/99200889-6062aa80-27a8-11eb-9a4e-3c9eaadc9bc6.png)

**Comment by bueltge** [comment]
same like this feedback - https://wordpress.org/support/topic/custom-site-icon-does-not-appear-in-the-admin-bar/#post-13666663
I will fix them shortly.

**Comment by bueltge** [comment]
Should be fixed.
