### ISSUE TITLE
Gallery block error

### ISSUE THREAD

**Issue by samykantari** [bueltge/wordpress-multisite-enhancements#69]
Hello, 

I tested this plugin on a empty WordPress. It is the only plugin installed and activated.
Everything works except the Gut gallery block 

For the test I used the default theme: "Twenty Twenty". 

Thank you for your help

![2021-02-05 15 14 55](https://user-images.githubusercontent.com/1969340/107045088-683d5400-67c5-11eb-9204-364b5e41d52b.gif)

WordPress version : 5.6.1
PHP version : 7.3

**Comment by bueltge** [comment]
I check them in several installs and no problems or errors. I mean you have a problem with the plugin [Multisite Global Media](https://github.com/bueltge/multisite-global-media). Please try it without the plugin MGM and also try MGM without Multisite Enhancements. Thanks for your feedback.

**Comment by samykantari** [comment]
Hi, 
I did a second test on a blank WordPress with only the "wordpress-multisite-enhancements" plugin and the problem is still there.

The problem is still related to the gallery block. 
- The block works well with the images belonging to the site. 
 ![2021-02-28 19 57 28](https://user-images.githubusercontent.com/1969340/109430029-61d67c80-79ff-11eb-8dc6-ca4d760cccb8.gif)

- But does not work with the global images
![2021-02-28 19 57 55](https://user-images.githubusercontent.com/1969340/109430043-787cd380-79ff-11eb-8a35-a78a07d85dfa.gif)

On the 2 gifs we can see a difference in the button to create a new gallery 
- the button is to create a new gallery for the images coming from the site
- the button is inserted in the publication when the media comes from the global site

I think when you go to the global media tab the context of the gallery is lost. This could explain the concern.

Yes I think my concern is the same as for ticket #119.

If you want me to test other things, tell me.

WordPress version : 5.6.2
PHP version : 7.3
Multisite Global Media version : 0.1.1

<img width="1642" alt="Capture d’écran 2021-02-28 à 19 50 30" src="https://user-images.githubusercontent.com/1969340/109429832-6a7a8300-79fe-11eb-9d3c-515a9c3f40b4.png">

**Comment by bueltge** [comment]
@samykantari However, If I understand your problem correctly, there is a problem only if the Multisite Global Media Plugin is active and in use. So we should add this bug report to the plugin MGM, not here at the Multisite Enhancement plugin, or?

**Comment by samykantari** [comment]
@bueltge  Yes, I did get the wrong repo. The concern is for the Multisite Global Media plugin only.

Would you like me to make a new issue on the right repo with a link to it?

**Comment by eangulus** [comment]
Same issue here. Can't add global Images for a Gallery Block.

**Comment by bueltge** [comment]
I close them because is a topic from another plugin. It is not in the case of this repository, this plugin here.
